version: '3.8'
services:
  cv:
    build: .
    image: ayuyydev/cv
    ports:
      - '5173:5173'
    container_name: ayuyydev-cv
    environment:
      - CHOKDIR_USEPOOLING=true
    volumes:
      ## share the src folder,
      ## so the vite app can watch the changes from your local environment
      - ./src:/home/node/app/src
      ## prevent overriding of node modules from the local machine through Docker
      - web_node_modules:/home/node/app/node_modules
volumes:
  web_node_modules: